<?php

namespace Tests\Unit\Services\Commands\NewGame;


use App\Models\Game;
use App\Services\Commands\NewGame\DefaultNewGameCommandHandler;
use App\Services\Commands\NewGame\NewGameResult;
use PHPUnit\Framework\TestCase;
use Tests\Doubles\Repositories\GameRepository\FakeGameRepository;

class DefaultNewGameCommandHandlerTest extends TestCase
{
    private DefaultNewGameCommandHandler $handler;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->handler = new DefaultNewGameCommandHandler(
            new FakeGameRepository()
        );
    }

    public function testItCreatesNewGameAndReturnsIdOfTheGame():  void
    {
        $actual = $this->handler->handle();
        $this->assertEquals(new NewGameResult(1), $actual);
    }
}
