<?php

namespace Tests\Unit\Services\Commands\NewGame;


use App\Models\Game;
use App\Services\Commands\NewGame\DefaultNewGameCommandHandler;
use App\Services\Commands\NewGame\NewGameResult;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class DefaultNewGameCommandHandlerTest extends TestCase
{
    use RefreshDatabase;

    private DefaultNewGameCommandHandler $handler;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->handler = new DefaultNewGameCommandHandler();
    }

    public function testItCreatesNewGameAndReturnsIdOfTheGame():  void
    {
        $this->assertNull(Game::first());

        $actual = $this->handler->handle();

        $first = Game::first();
        $this->assertNotNull($first);
        $this->assertEquals(new NewGameResult($first->id), $actual);
    }
}
